apiVersion: apps/v1
kind: Deployment
metadata:
  name: outstagram-frontend
  namespace: outstagram
spec:
  replicas: 1
  selector:
    matchLabels:
      app: outstagram-frontend
  template:
    metadata:
      labels:
        app: outstagram-frontend
    spec:
      containers:
        - name: outstagram-frontend
          image: maewakka/outstagram-frontend:1.0.0
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: outstagram-frontend
  namespace: outstagram
spec:
  selector:
    app: outstagram-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 31444
  type: NodePort